language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: PmJT2zgkkJontp5wGzJrAWQHWSARLeBR5RqWg4VYFhnThqRoxa69DBd4SZmicuB6imaya6KaY/ipz6fJah+JvLyblSuU7FavGWYMgmrzGUVccRU3jFqdceqqaulX44hzVODjRE5siLN1YYyIb3A8HEXqxMSmdK/1+b9JftQRCRNbEA1MdeDUJSKc3YAJfYoz5hwB/02nT1Ui0eosCXyvrlT5NlskTrM/oPabaE3WWvIZJ3+DD0B2JpxT8VxgB0p+tok7MiBygK5S3mEWIvxLB3dwrr92RuqZ4t44wtsRE/GJxqBtNtxgYVagUScCSLFXbr5U2VZY3pOr8aAp6Hip2MwkUiWqiTeqBdt7Aq07AeDJUDr6SlaEKuXMkchi5h2ys8ATW96aHYdmcLpQ45NVTWSw3Dxog2HAvp3ZAQtavbjoIs8LFaixGPh67SvyzBxZdls9GFU7J3wGTdMQXcVVyuNa2OgLlNDlmlQteOzEkh04F9ZD0xllFkNMv+ZsEt51qxGH2TJzzHTteG5l+HVJZybE8yaTqgTvcIwpJFOpywywXJdEsnuUQ0/I/+kDSnkTQ+o6tytvOmqF3P4PeMESu5MbuvQUwnaZqeH+gZYOnfEJ5W/ev252YAcBQfXgW0sMk0n74YGmNIyyzWJUkWNNH4gq+IFgUmkZv9bZc772B/Q=
  strategy: git
  app: streetartwalk
  on:
    repo: StreetArtMap/streetArtMap
  skip_cleanup: true
