language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: RTBQTkZyTIAqamHIIuyx3zmA5ZvEfdYY100rDYgKtBOmOS1Tuv6HSuDyrDeWBqrXn+vz+xgwxsTbx8Ow1tZEqBlm/nzgVafbpQ72hqu0NddFWJCrHOjxdK+6A6WQ+kfwzqKaFqUX1yXHL4PkIimanIIHg2x1TsvkqsIeZDtxn/yupl4lWRAVs0Wb08sBUMTzJKm6CmtAb3iWBSepefHmyOHyeTzgPgmcFzYoi/Mcgx8YumG4QjRafzH7doe6Bt1wQvXmXT2jd8Zy+T9SWnrMlPDlr5Z7Kqx2HXnI5cvhkRjMUXXed5ZKD2Tf2uov197WBlO+4tkW4F1Q46l/gYyLKqx3TP0Nmgq51wAkoZ9rKRWYZpWKH3TFJbICdgaGBWVo4zhg7/nX/XSPHfKnIjBMO+Qn8AM7Bvq9NrxbS1TWZo+bk/R9LapTDeuR+Jjuf104dmVUs+HQLyRMjP21vkeKgyVtNsAZEOFL5jooTUsLC3EUlPIWGjsdkCTH8luOOnaIU3BWXE97ZQ/DirR6+mIRat3sqqasZ12VlG3+O6Abw07ZAXZNx5BxrCX/xoNVBvLM/ELqQdX73PnpZg8aDS271o2z/xji3rUN2JwAHciBAeTmEeBEG9ZdaG4+Ydh34fKS/FlhC7MdFhb9TJWzm1JxqKg04SLsdlSZy8Z+7qSieeQ=
  app: streetArtMap
  on:
    repo: StreetArtMap/streetArtMap
  skip_cleanup: 'true'
