language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: q+oNg4NqqWhMOw1qAS7uo71rPO1niqmEGDpA78t3gG5KcIveQH23V+fOBxCyX/YgInDiAqhHYAj6QWhFLuz8e+VwmetM5mXTIV4tNFAlHR4FsDk7QnVM2BlNUQo2Kn+7Tgspt1LaDS0UnwBvwWtSqCOPwcMz3r5d5AD2bi2kJiEaa18GvRVQC1fXHbOXF78n9XU4z2s4ND76Bs5cgUlonH80O+oM6GyOjxsF0rXFd9hf7x6HWrtsP9e0tWSzq3o/Kk+tBcg9pFoR05jbG7dPeA7cssXEP1MJ23nSirdvaRxNvya6EjeDOlLrvZ4Y4v4u9yOBDJvQt8sTpPovsQzKyxsQmhKpuPD28ScfkCTm2UCh5H4FuHdOLBDlmvKSeSzbiw0fN8eY/UM1RO/3xVYrIzdOalBuRu4udvKfAcE5R1OY9/m3IAuDz04tPIHybSZ5FCjv3eZN0TAU77xPG+4mUZLAHDSoYQVDxT5Nf7QZlC07QnZEVoclmA17hsxSFV8bIjh18X5Ya1pRiWy/HhlcsAEn82llpye14CvtyI/cP86v/J3hxzxcEzYtqNU+9CsndlOjmSwLyBQYIHWemA0J4hkKtv4eL5oFWxUH81HaZW/LLk9xPqtyJ5LHFyEZ/HyYlLZFmfLdEgnJ8FkKsXFCIODWx4auy325pAVZzoTil1s=
  app: streetArtWalk
  on:
    repo: StreetArtMap/streetArtMap
  skip_cleanup: 'true'
